// Code generated by "stringer -type=PeerState"; DO NOT EDIT.

package p2p

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[DIRTY-1]
	_ = x[SYNCED-2]
}

const _PeerState_name = "UNKNOWNDIRTYSYNCED"

var _PeerState_index = [...]uint8{0, 7, 12, 18}

func (i PeerState) String() string {
	if i >= PeerState(len(_PeerState_index)-1) {
		return "PeerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PeerState_name[_PeerState_index[i]:_PeerState_index[i+1]]
}
