// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Op int32

const (
	// Adds the target triple to the target graph
	Op_ADD Op = 0
	// Deletes the target triple from the target graph
	Op_DEL Op = 1
	// Commits the outstanding log entries to a new version
	Op_FLUSH Op = 2
	// opens the given file and loads it into the target graph
	Op_REGISTER_TRIGGER Op = 3
)

var Op_name = map[int32]string{
	0: "ADD",
	1: "DEL",
	2: "FLUSH",
	3: "REGISTER_TRIGGER",
}

var Op_value = map[string]int32{
	"ADD":              0,
	"DEL":              1,
	"FLUSH":            2,
	"REGISTER_TRIGGER": 3,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

type TimeFilter int32

const (
	TimeFilter_At     TimeFilter = 0
	TimeFilter_Before TimeFilter = 1
	TimeFilter_After  TimeFilter = 2
)

var TimeFilter_name = map[int32]string{
	0: "At",
	1: "Before",
	2: "After",
}

var TimeFilter_value = map[string]int32{
	"At":     0,
	"Before": 1,
	"After":  2,
}

func (x TimeFilter) String() string {
	return proto.EnumName(TimeFilter_name, int32(x))
}

func (TimeFilter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

type Pattern int32

const (
	Pattern_Single   Pattern = 0
	Pattern_ZeroOne  Pattern = 1
	Pattern_ZeroPlus Pattern = 2
	Pattern_OnePlus  Pattern = 3
)

var Pattern_name = map[int32]string{
	0: "Single",
	1: "ZeroOne",
	2: "ZeroPlus",
	3: "OnePlus",
}

var Pattern_value = map[string]int32{
	"Single":   0,
	"ZeroOne":  1,
	"ZeroPlus": 2,
	"OnePlus":  3,
}

func (x Pattern) String() string {
	return proto.EnumName(Pattern_name, int32(x))
}

func (Pattern) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Variables            []string `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty"`
	Rows                 []*Row   `protobuf:"bytes,5,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Response) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Response) GetVariables() []string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *Response) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type URI struct {
	// full URI
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// variable
	Variable             string   `protobuf:"bytes,3,opt,name=variable,proto3" json:"variable,omitempty"`
	Pattern              Pattern  `protobuf:"varint,4,opt,name=pattern,proto3,enum=proto.Pattern" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URI) Reset()         { *m = URI{} }
func (m *URI) String() string { return proto.CompactTextString(m) }
func (*URI) ProtoMessage()    {}
func (*URI) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}
func (m *URI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URI.Unmarshal(m, b)
}
func (m *URI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URI.Marshal(b, m, deterministic)
}
func (m *URI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URI.Merge(m, src)
}
func (m *URI) XXX_Size() int {
	return xxx_messageInfo_URI.Size(m)
}
func (m *URI) XXX_DiscardUnknown() {
	xxx_messageInfo_URI.DiscardUnknown(m)
}

var xxx_messageInfo_URI proto.InternalMessageInfo

func (m *URI) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *URI) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *URI) GetVariable() string {
	if m != nil {
		return m.Variable
	}
	return ""
}

func (m *URI) GetPattern() Pattern {
	if m != nil {
		return m.Pattern
	}
	return Pattern_Single
}

type LogEntry struct {
	// operation of the log
	Op Op `protobuf:"varint,1,opt,name=op,proto3,enum=proto.Op" json:"op,omitempty"`
	// the graph this applies to
	Graph string `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	// timestamp of the version. Used during COMMIT
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// source tag
	Tag string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	// Triple that is the subject of the operation
	Triple *Triple `protobuf:"bytes,5,opt,name=triple,proto3" json:"triple,omitempty"`
	// when this is true, seal the version as all uncommitted
	// log entries since the last commit=true entry
	Commit bool `protobuf:"varint,6,opt,name=commit,proto3" json:"commit,omitempty"`
	// Triggers
	Trigger              *Trigger `protobuf:"bytes,7,opt,name=trigger,proto3" json:"trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_ADD
}

func (m *LogEntry) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *LogEntry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LogEntry) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *LogEntry) GetTriple() *Triple {
	if m != nil {
		return m.Triple
	}
	return nil
}

func (m *LogEntry) GetCommit() bool {
	if m != nil {
		return m.Commit
	}
	return false
}

func (m *LogEntry) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

type Triple struct {
	Subject              *URI     `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            []*URI   `protobuf:"bytes,2,rep,name=predicate,proto3" json:"predicate,omitempty"`
	Object               *URI     `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Triple) Reset()         { *m = Triple{} }
func (m *Triple) String() string { return proto.CompactTextString(m) }
func (*Triple) ProtoMessage()    {}
func (*Triple) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}
func (m *Triple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Triple.Unmarshal(m, b)
}
func (m *Triple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Triple.Marshal(b, m, deterministic)
}
func (m *Triple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Triple.Merge(m, src)
}
func (m *Triple) XXX_Size() int {
	return xxx_messageInfo_Triple.Size(m)
}
func (m *Triple) XXX_DiscardUnknown() {
	xxx_messageInfo_Triple.DiscardUnknown(m)
}

var xxx_messageInfo_Triple proto.InternalMessageInfo

func (m *Triple) GetSubject() *URI {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Triple) GetPredicate() []*URI {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *Triple) GetObject() *URI {
	if m != nil {
		return m.Object
	}
	return nil
}

type SelectQuery struct {
	// list of vars to select, including '*'
	Vars []string `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty"`
	// list of graphs to select, including '*'
	Graphs []string `protobuf:"bytes,2,rep,name=graphs,proto3" json:"graphs,omitempty"`
	// time filter
	Filter    TimeFilter `protobuf:"varint,3,opt,name=filter,proto3,enum=proto.TimeFilter" json:"filter,omitempty"`
	Timestamp int64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// where clause
	Where                []*Triple `protobuf:"bytes,5,rep,name=where,proto3" json:"where,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SelectQuery) Reset()         { *m = SelectQuery{} }
func (m *SelectQuery) String() string { return proto.CompactTextString(m) }
func (*SelectQuery) ProtoMessage()    {}
func (*SelectQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}
func (m *SelectQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectQuery.Unmarshal(m, b)
}
func (m *SelectQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectQuery.Marshal(b, m, deterministic)
}
func (m *SelectQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectQuery.Merge(m, src)
}
func (m *SelectQuery) XXX_Size() int {
	return xxx_messageInfo_SelectQuery.Size(m)
}
func (m *SelectQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SelectQuery proto.InternalMessageInfo

func (m *SelectQuery) GetVars() []string {
	if m != nil {
		return m.Vars
	}
	return nil
}

func (m *SelectQuery) GetGraphs() []string {
	if m != nil {
		return m.Graphs
	}
	return nil
}

func (m *SelectQuery) GetFilter() TimeFilter {
	if m != nil {
		return m.Filter
	}
	return TimeFilter_At
}

func (m *SelectQuery) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SelectQuery) GetWhere() []*Triple {
	if m != nil {
		return m.Where
	}
	return nil
}

type InsertQuery struct {
	// insert terms
	Insert []*Triple `protobuf:"bytes,1,rep,name=insert,proto3" json:"insert,omitempty"`
	// list of graphs to insert into, including '*'
	Graphs []string `protobuf:"bytes,2,rep,name=graphs,proto3" json:"graphs,omitempty"`
	// where clause
	Where []*Triple `protobuf:"bytes,3,rep,name=where,proto3" json:"where,omitempty"`
	// whether or not to wait for flush to disk
	Blocking             bool     `protobuf:"varint,4,opt,name=blocking,proto3" json:"blocking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertQuery) Reset()         { *m = InsertQuery{} }
func (m *InsertQuery) String() string { return proto.CompactTextString(m) }
func (*InsertQuery) ProtoMessage()    {}
func (*InsertQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5}
}
func (m *InsertQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertQuery.Unmarshal(m, b)
}
func (m *InsertQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertQuery.Marshal(b, m, deterministic)
}
func (m *InsertQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertQuery.Merge(m, src)
}
func (m *InsertQuery) XXX_Size() int {
	return xxx_messageInfo_InsertQuery.Size(m)
}
func (m *InsertQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertQuery.DiscardUnknown(m)
}

var xxx_messageInfo_InsertQuery proto.InternalMessageInfo

func (m *InsertQuery) GetInsert() []*Triple {
	if m != nil {
		return m.Insert
	}
	return nil
}

func (m *InsertQuery) GetGraphs() []string {
	if m != nil {
		return m.Graphs
	}
	return nil
}

func (m *InsertQuery) GetWhere() []*Triple {
	if m != nil {
		return m.Where
	}
	return nil
}

func (m *InsertQuery) GetBlocking() bool {
	if m != nil {
		return m.Blocking
	}
	return false
}

type VersionQuery struct {
	Filter               TimeFilter `protobuf:"varint,1,opt,name=filter,proto3,enum=proto.TimeFilter" json:"filter,omitempty"`
	Graphs               []string   `protobuf:"bytes,2,rep,name=graphs,proto3" json:"graphs,omitempty"`
	Limit                int64      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VersionQuery) Reset()         { *m = VersionQuery{} }
func (m *VersionQuery) String() string { return proto.CompactTextString(m) }
func (*VersionQuery) ProtoMessage()    {}
func (*VersionQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{6}
}
func (m *VersionQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionQuery.Unmarshal(m, b)
}
func (m *VersionQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionQuery.Marshal(b, m, deterministic)
}
func (m *VersionQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionQuery.Merge(m, src)
}
func (m *VersionQuery) XXX_Size() int {
	return xxx_messageInfo_VersionQuery.Size(m)
}
func (m *VersionQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionQuery.DiscardUnknown(m)
}

var xxx_messageInfo_VersionQuery proto.InternalMessageInfo

func (m *VersionQuery) GetFilter() TimeFilter {
	if m != nil {
		return m.Filter
	}
	return TimeFilter_At
}

func (m *VersionQuery) GetGraphs() []string {
	if m != nil {
		return m.Graphs
	}
	return nil
}

func (m *VersionQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Entity struct {
	EntityKey []byte `protobuf:"bytes,1,opt,name=EntityKey,proto3" json:"EntityKey,omitempty"`
	// handles 1-hop and + and *
	In                   []*Entity_Edge      `protobuf:"bytes,2,rep,name=in,proto3" json:"in,omitempty"`
	Out                  []*Entity_Edge      `protobuf:"bytes,3,rep,name=out,proto3" json:"out,omitempty"`
	Endpoints            []*Entity_Endpoints `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{7}
}
func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetEntityKey() []byte {
	if m != nil {
		return m.EntityKey
	}
	return nil
}

func (m *Entity) GetIn() []*Entity_Edge {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *Entity) GetOut() []*Entity_Edge {
	if m != nil {
		return m.Out
	}
	return nil
}

func (m *Entity) GetEndpoints() []*Entity_Endpoints {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// for nodes
type Entity_Edge struct {
	Predicate            []byte   `protobuf:"bytes,1,opt,name=Predicate,proto3" json:"Predicate,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Pattern              Pattern  `protobuf:"varint,3,opt,name=Pattern,proto3,enum=proto.Pattern" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity_Edge) Reset()         { *m = Entity_Edge{} }
func (m *Entity_Edge) String() string { return proto.CompactTextString(m) }
func (*Entity_Edge) ProtoMessage()    {}
func (*Entity_Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{7, 0}
}
func (m *Entity_Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity_Edge.Unmarshal(m, b)
}
func (m *Entity_Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity_Edge.Marshal(b, m, deterministic)
}
func (m *Entity_Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity_Edge.Merge(m, src)
}
func (m *Entity_Edge) XXX_Size() int {
	return xxx_messageInfo_Entity_Edge.Size(m)
}
func (m *Entity_Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Entity_Edge proto.InternalMessageInfo

func (m *Entity_Edge) GetPredicate() []byte {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *Entity_Edge) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Entity_Edge) GetPattern() Pattern {
	if m != nil {
		return m.Pattern
	}
	return Pattern_Single
}

// for edges
type Entity_Endpoints struct {
	Src                  []byte   `protobuf:"bytes,1,opt,name=Src,proto3" json:"Src,omitempty"`
	Dst                  []byte   `protobuf:"bytes,2,opt,name=Dst,proto3" json:"Dst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity_Endpoints) Reset()         { *m = Entity_Endpoints{} }
func (m *Entity_Endpoints) String() string { return proto.CompactTextString(m) }
func (*Entity_Endpoints) ProtoMessage()    {}
func (*Entity_Endpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{7, 1}
}
func (m *Entity_Endpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity_Endpoints.Unmarshal(m, b)
}
func (m *Entity_Endpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity_Endpoints.Marshal(b, m, deterministic)
}
func (m *Entity_Endpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity_Endpoints.Merge(m, src)
}
func (m *Entity_Endpoints) XXX_Size() int {
	return xxx_messageInfo_Entity_Endpoints.Size(m)
}
func (m *Entity_Endpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity_Endpoints.DiscardUnknown(m)
}

var xxx_messageInfo_Entity_Endpoints proto.InternalMessageInfo

func (m *Entity_Endpoints) GetSrc() []byte {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Entity_Endpoints) GetDst() []byte {
	if m != nil {
		return m.Dst
	}
	return nil
}

type Row struct {
	Values               []*URI   `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{8}
}
func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetValues() []*URI {
	if m != nil {
		return m.Values
	}
	return nil
}

type TagInsertRequest struct {
	Graph                string    `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	Tag                  string    `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Triples              []*Triple `protobuf:"bytes,3,rep,name=triples,proto3" json:"triples,omitempty"`
	Operation            Op        `protobuf:"varint,4,opt,name=operation,proto3,enum=proto.Op" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TagInsertRequest) Reset()         { *m = TagInsertRequest{} }
func (m *TagInsertRequest) String() string { return proto.CompactTextString(m) }
func (*TagInsertRequest) ProtoMessage()    {}
func (*TagInsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{9}
}
func (m *TagInsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagInsertRequest.Unmarshal(m, b)
}
func (m *TagInsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagInsertRequest.Marshal(b, m, deterministic)
}
func (m *TagInsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagInsertRequest.Merge(m, src)
}
func (m *TagInsertRequest) XXX_Size() int {
	return xxx_messageInfo_TagInsertRequest.Size(m)
}
func (m *TagInsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagInsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagInsertRequest proto.InternalMessageInfo

func (m *TagInsertRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *TagInsertRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TagInsertRequest) GetTriples() []*Triple {
	if m != nil {
		return m.Triples
	}
	return nil
}

func (m *TagInsertRequest) GetOperation() Op {
	if m != nil {
		return m.Operation
	}
	return Op_ADD
}

type TagInsertResponse struct {
	// error that ocurred, if any
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// if true, the inserts were processed; else, the tag was the ignored
	Processed bool `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
	// the version these inserts were added to
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagInsertResponse) Reset()         { *m = TagInsertResponse{} }
func (m *TagInsertResponse) String() string { return proto.CompactTextString(m) }
func (*TagInsertResponse) ProtoMessage()    {}
func (*TagInsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{10}
}
func (m *TagInsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagInsertResponse.Unmarshal(m, b)
}
func (m *TagInsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagInsertResponse.Marshal(b, m, deterministic)
}
func (m *TagInsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagInsertResponse.Merge(m, src)
}
func (m *TagInsertResponse) XXX_Size() int {
	return xxx_messageInfo_TagInsertResponse.Size(m)
}
func (m *TagInsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagInsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagInsertResponse proto.InternalMessageInfo

func (m *TagInsertResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TagInsertResponse) GetProcessed() bool {
	if m != nil {
		return m.Processed
	}
	return false
}

func (m *TagInsertResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Trigger struct {
	Graph                string    `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Where                []*Triple `protobuf:"bytes,3,rep,name=where,proto3" json:"where,omitempty"`
	Insert               []*Triple `protobuf:"bytes,4,rep,name=insert,proto3" json:"insert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{11}
}
func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetWhere() []*Triple {
	if m != nil {
		return m.Where
	}
	return nil
}

func (m *Trigger) GetInsert() []*Triple {
	if m != nil {
		return m.Insert
	}
	return nil
}

type RegisterTriggerRequest struct {
	Trigger              *Trigger `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTriggerRequest) Reset()         { *m = RegisterTriggerRequest{} }
func (m *RegisterTriggerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterTriggerRequest) ProtoMessage()    {}
func (*RegisterTriggerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{12}
}
func (m *RegisterTriggerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTriggerRequest.Unmarshal(m, b)
}
func (m *RegisterTriggerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTriggerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterTriggerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTriggerRequest.Merge(m, src)
}
func (m *RegisterTriggerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterTriggerRequest.Size(m)
}
func (m *RegisterTriggerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTriggerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTriggerRequest proto.InternalMessageInfo

func (m *RegisterTriggerRequest) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

type DeleteTriggerRequest struct {
	Graph                string   `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTriggerRequest) Reset()         { *m = DeleteTriggerRequest{} }
func (m *DeleteTriggerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTriggerRequest) ProtoMessage()    {}
func (*DeleteTriggerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{13}
}
func (m *DeleteTriggerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTriggerRequest.Unmarshal(m, b)
}
func (m *DeleteTriggerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTriggerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTriggerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTriggerRequest.Merge(m, src)
}
func (m *DeleteTriggerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTriggerRequest.Size(m)
}
func (m *DeleteTriggerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTriggerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTriggerRequest proto.InternalMessageInfo

func (m *DeleteTriggerRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *DeleteTriggerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListTriggersRequest struct {
	Graph string `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	// if name is empty, return all triggers
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTriggersRequest) Reset()         { *m = ListTriggersRequest{} }
func (m *ListTriggersRequest) String() string { return proto.CompactTextString(m) }
func (*ListTriggersRequest) ProtoMessage()    {}
func (*ListTriggersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{14}
}
func (m *ListTriggersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTriggersRequest.Unmarshal(m, b)
}
func (m *ListTriggersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTriggersRequest.Marshal(b, m, deterministic)
}
func (m *ListTriggersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTriggersRequest.Merge(m, src)
}
func (m *ListTriggersRequest) XXX_Size() int {
	return xxx_messageInfo_ListTriggersRequest.Size(m)
}
func (m *ListTriggersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTriggersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTriggersRequest proto.InternalMessageInfo

func (m *ListTriggersRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *ListTriggersRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TriggerResponse struct {
	Error                string     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Triggers             []*Trigger `protobuf:"bytes,2,rep,name=triggers,proto3" json:"triggers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TriggerResponse) Reset()         { *m = TriggerResponse{} }
func (m *TriggerResponse) String() string { return proto.CompactTextString(m) }
func (*TriggerResponse) ProtoMessage()    {}
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{15}
}
func (m *TriggerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerResponse.Unmarshal(m, b)
}
func (m *TriggerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerResponse.Marshal(b, m, deterministic)
}
func (m *TriggerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerResponse.Merge(m, src)
}
func (m *TriggerResponse) XXX_Size() int {
	return xxx_messageInfo_TriggerResponse.Size(m)
}
func (m *TriggerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerResponse proto.InternalMessageInfo

func (m *TriggerResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TriggerResponse) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*URI)(nil), "proto.URI")
	proto.RegisterType((*LogEntry)(nil), "proto.LogEntry")
	proto.RegisterType((*Triple)(nil), "proto.Triple")
	proto.RegisterType((*SelectQuery)(nil), "proto.SelectQuery")
	proto.RegisterType((*InsertQuery)(nil), "proto.InsertQuery")
	proto.RegisterType((*VersionQuery)(nil), "proto.VersionQuery")
	proto.RegisterType((*Entity)(nil), "proto.Entity")
	proto.RegisterType((*Entity_Edge)(nil), "proto.Entity.Edge")
	proto.RegisterType((*Entity_Endpoints)(nil), "proto.Entity.Endpoints")
	proto.RegisterType((*Row)(nil), "proto.Row")
	proto.RegisterType((*TagInsertRequest)(nil), "proto.TagInsertRequest")
	proto.RegisterType((*TagInsertResponse)(nil), "proto.TagInsertResponse")
	proto.RegisterType((*Trigger)(nil), "proto.Trigger")
	proto.RegisterType((*RegisterTriggerRequest)(nil), "proto.RegisterTriggerRequest")
	proto.RegisterType((*DeleteTriggerRequest)(nil), "proto.DeleteTriggerRequest")
	proto.RegisterType((*ListTriggersRequest)(nil), "proto.ListTriggersRequest")
	proto.RegisterType((*TriggerResponse)(nil), "proto.TriggerResponse")
	proto.RegisterEnum("proto.Op", Op_name, Op_value)
	proto.RegisterEnum("proto.TimeFilter", TimeFilter_name, TimeFilter_value)
	proto.RegisterEnum("proto.Pattern", Pattern_name, Pattern_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HodDBClient is the client API for HodDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HodDBClient interface {
	Select(ctx context.Context, in *SelectQuery, opts ...grpc.CallOption) (*Response, error)
	Count(ctx context.Context, in *SelectQuery, opts ...grpc.CallOption) (*Response, error)
	Versions(ctx context.Context, in *VersionQuery, opts ...grpc.CallOption) (*Response, error)
	TagInsert(ctx context.Context, in *TagInsertRequest, opts ...grpc.CallOption) (*TagInsertResponse, error)
	RegisterTrigger(ctx context.Context, in *RegisterTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	DeleteTrigger(ctx context.Context, in *DeleteTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	ListTriggers(ctx context.Context, in *ListTriggersRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
}

type hodDBClient struct {
	cc *grpc.ClientConn
}

func NewHodDBClient(cc *grpc.ClientConn) HodDBClient {
	return &hodDBClient{cc}
}

func (c *hodDBClient) Select(ctx context.Context, in *SelectQuery, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.HodDB/Select", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hodDBClient) Count(ctx context.Context, in *SelectQuery, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.HodDB/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hodDBClient) Versions(ctx context.Context, in *VersionQuery, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.HodDB/Versions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hodDBClient) TagInsert(ctx context.Context, in *TagInsertRequest, opts ...grpc.CallOption) (*TagInsertResponse, error) {
	out := new(TagInsertResponse)
	err := c.cc.Invoke(ctx, "/proto.HodDB/TagInsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hodDBClient) RegisterTrigger(ctx context.Context, in *RegisterTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, "/proto.HodDB/RegisterTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hodDBClient) DeleteTrigger(ctx context.Context, in *DeleteTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, "/proto.HodDB/DeleteTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hodDBClient) ListTriggers(ctx context.Context, in *ListTriggersRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, "/proto.HodDB/ListTriggers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HodDBServer is the server API for HodDB service.
type HodDBServer interface {
	Select(context.Context, *SelectQuery) (*Response, error)
	Count(context.Context, *SelectQuery) (*Response, error)
	Versions(context.Context, *VersionQuery) (*Response, error)
	TagInsert(context.Context, *TagInsertRequest) (*TagInsertResponse, error)
	RegisterTrigger(context.Context, *RegisterTriggerRequest) (*TriggerResponse, error)
	DeleteTrigger(context.Context, *DeleteTriggerRequest) (*TriggerResponse, error)
	ListTriggers(context.Context, *ListTriggersRequest) (*TriggerResponse, error)
}

func RegisterHodDBServer(s *grpc.Server, srv HodDBServer) {
	s.RegisterService(&_HodDB_serviceDesc, srv)
}

func _HodDB_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/Select",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).Select(ctx, req.(*SelectQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _HodDB_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).Count(ctx, req.(*SelectQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _HodDB_Versions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).Versions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/Versions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).Versions(ctx, req.(*VersionQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _HodDB_TagInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).TagInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/TagInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).TagInsert(ctx, req.(*TagInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HodDB_RegisterTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).RegisterTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/RegisterTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).RegisterTrigger(ctx, req.(*RegisterTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HodDB_DeleteTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).DeleteTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/DeleteTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).DeleteTrigger(ctx, req.(*DeleteTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HodDB_ListTriggers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTriggersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).ListTriggers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/ListTriggers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).ListTriggers(ctx, req.(*ListTriggersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HodDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HodDB",
	HandlerType: (*HodDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Select",
			Handler:    _HodDB_Select_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _HodDB_Count_Handler,
		},
		{
			MethodName: "Versions",
			Handler:    _HodDB_Versions_Handler,
		},
		{
			MethodName: "TagInsert",
			Handler:    _HodDB_TagInsert_Handler,
		},
		{
			MethodName: "RegisterTrigger",
			Handler:    _HodDB_RegisterTrigger_Handler,
		},
		{
			MethodName: "DeleteTrigger",
			Handler:    _HodDB_DeleteTrigger_Handler,
		},
		{
			MethodName: "ListTriggers",
			Handler:    _HodDB_ListTriggers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 1065 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0x5f, 0xdb, 0x89, 0x13, 0x9f, 0x74, 0xbb, 0xde, 0xd9, 0xaa, 0x7f, 0xff, 0xc3, 0x82, 0x22,
	0xb3, 0xab, 0xcd, 0x16, 0x28, 0x28, 0x08, 0x71, 0xc5, 0x47, 0x4b, 0xb2, 0x6d, 0x45, 0xa5, 0x96,
	0x49, 0xbb, 0x17, 0xdc, 0x20, 0x37, 0x39, 0xf5, 0x1a, 0x1c, 0x8f, 0x99, 0x99, 0xb4, 0xaa, 0x84,
	0xb4, 0x2f, 0x00, 0xbc, 0x06, 0x12, 0x0f, 0xc1, 0x53, 0xf0, 0x40, 0x68, 0xc6, 0x63, 0x3b, 0x4d,
	0x9b, 0x52, 0xae, 0x32, 0xe7, 0xfc, 0xce, 0x9c, 0xaf, 0x39, 0xe7, 0xe7, 0x80, 0x97, 0xb2, 0x78,
	0x3b, 0xe7, 0x4c, 0x32, 0xd2, 0xd4, 0x3f, 0xe1, 0xef, 0x16, 0xb4, 0x29, 0x8a, 0x9c, 0x65, 0x02,
	0xc9, 0x06, 0x34, 0x91, 0x73, 0xc6, 0x03, 0xab, 0x67, 0xf5, 0x3d, 0x5a, 0x08, 0x24, 0x80, 0xd6,
	0x05, 0x72, 0x91, 0xb0, 0x2c, 0xb0, 0x7b, 0x56, 0xdf, 0xa1, 0xa5, 0xa8, 0xec, 0x27, 0x6c, 0x9e,
	0xc9, 0xc0, 0xd1, 0xfa, 0x42, 0x20, 0x4f, 0xc1, 0xbb, 0x88, 0x78, 0x12, 0x9d, 0xa5, 0x28, 0x82,
	0x46, 0xcf, 0xe9, 0x7b, 0xb4, 0x56, 0x90, 0xf7, 0xa0, 0xc1, 0xd9, 0xa5, 0x08, 0x9a, 0x3d, 0xa7,
	0xdf, 0x19, 0x40, 0x91, 0xcd, 0x36, 0x65, 0x97, 0x54, 0xeb, 0xc3, 0xb7, 0xe0, 0x9c, 0xd2, 0x03,
	0xe5, 0x24, 0x8b, 0x66, 0x28, 0xf2, 0x68, 0x82, 0x26, 0x9d, 0x5a, 0xa1, 0x02, 0x5f, 0x44, 0xe9,
	0x1c, 0x75, 0x42, 0x1e, 0x2d, 0x04, 0xd2, 0x85, 0x76, 0x19, 0x47, 0x67, 0xe4, 0xd1, 0x4a, 0x26,
	0x7d, 0x68, 0xe5, 0x91, 0x94, 0xc8, 0xb3, 0xa0, 0xd1, 0xb3, 0xfa, 0xeb, 0x83, 0x75, 0x13, 0xf9,
	0xb8, 0xd0, 0xd2, 0x12, 0x0e, 0xff, 0xb6, 0xa0, 0x7d, 0xc8, 0xe2, 0x51, 0x26, 0xf9, 0x15, 0xf9,
	0x3f, 0xd8, 0x2c, 0xd7, 0xf1, 0xd7, 0x07, 0x9e, 0xb9, 0x71, 0x94, 0x53, 0x9b, 0xe5, 0x2a, 0x87,
	0x98, 0x47, 0xf9, 0x9b, 0x32, 0x07, 0x2d, 0xa8, 0xbc, 0x65, 0x32, 0x43, 0x21, 0xa3, 0x59, 0x6e,
	0xda, 0x52, 0x2b, 0x88, 0x0f, 0x8e, 0x8c, 0x62, 0x9d, 0x81, 0x47, 0xd5, 0x91, 0x3c, 0x07, 0x57,
	0xf2, 0x24, 0x4f, 0x31, 0x68, 0xf6, 0xac, 0x7e, 0x67, 0xf0, 0xd0, 0x04, 0x39, 0xd1, 0x4a, 0x6a,
	0x40, 0xb2, 0x09, 0xee, 0x84, 0xcd, 0x66, 0x89, 0x0c, 0xdc, 0x9e, 0xd5, 0x6f, 0x53, 0x23, 0xa9,
	0xb2, 0x24, 0x4f, 0xe2, 0x18, 0x79, 0xd0, 0xd2, 0xf7, 0xd7, 0xeb, 0xfb, 0x4a, 0x4b, 0x4b, 0x38,
	0xfc, 0x05, 0xdc, 0xc2, 0x27, 0x79, 0x06, 0x2d, 0x31, 0x3f, 0xfb, 0x11, 0x27, 0x52, 0x17, 0x56,
	0x3f, 0xc2, 0x29, 0x3d, 0xa0, 0x25, 0x44, 0xfa, 0xe0, 0xe5, 0x1c, 0xa7, 0xc9, 0x24, 0x92, 0xaa,
	0xcd, 0xce, 0x92, 0x5d, 0x0d, 0x92, 0x10, 0x5c, 0x56, 0xb8, 0x73, 0x6e, 0xb8, 0x33, 0x48, 0xf8,
	0x87, 0x05, 0x9d, 0x31, 0xa6, 0x38, 0x91, 0xdf, 0xcd, 0x91, 0x5f, 0x11, 0x02, 0x8d, 0x8b, 0x88,
	0x8b, 0xc0, 0xd2, 0xe3, 0xa1, 0xcf, 0xaa, 0x46, 0xdd, 0x43, 0xa1, 0xc3, 0x79, 0xd4, 0x48, 0xe4,
	0x25, 0xb8, 0xe7, 0x49, 0x2a, 0x91, 0x6b, 0xff, 0xeb, 0x83, 0xc7, 0x65, 0x89, 0xc9, 0x0c, 0x5f,
	0x69, 0x80, 0x1a, 0x83, 0xeb, 0xdd, 0x6f, 0x2c, 0x77, 0xff, 0x7d, 0x68, 0x5e, 0xbe, 0x41, 0x8e,
	0x66, 0xf6, 0x96, 0x5a, 0x5d, 0x60, 0xe1, 0x6f, 0x16, 0x74, 0x0e, 0x32, 0x81, 0xdc, 0x64, 0xfa,
	0x1c, 0xdc, 0x44, 0x8b, 0x3a, 0xd7, 0x9b, 0x0f, 0x54, 0x80, 0x2b, 0x93, 0xaf, 0x62, 0x3a, 0xab,
	0x63, 0xaa, 0xc1, 0x3d, 0x4b, 0xd9, 0xe4, 0xa7, 0x24, 0x2b, 0x66, 0xa3, 0x4d, 0x2b, 0x39, 0x8c,
	0x61, 0xed, 0x75, 0xb1, 0x6e, 0x45, 0x3e, 0x75, 0x37, 0xac, 0x7f, 0xeb, 0xc6, 0xaa, 0x9c, 0x36,
	0xa0, 0x99, 0x26, 0x6a, 0x96, 0xcc, 0xda, 0x6a, 0x21, 0xfc, 0xcb, 0x06, 0x77, 0x94, 0xc9, 0x44,
	0x5e, 0xa9, 0x36, 0x16, 0xa7, 0x6f, 0xf1, 0x4a, 0x87, 0x59, 0xa3, 0xb5, 0x82, 0x84, 0x60, 0x27,
	0x99, 0x19, 0x09, 0x62, 0xa2, 0x17, 0xe8, 0xf6, 0x68, 0x1a, 0x23, 0xb5, 0x93, 0x8c, 0x3c, 0x03,
	0x87, 0xcd, 0xa5, 0x29, 0xfa, 0x36, 0x23, 0x05, 0x93, 0xcf, 0xc0, 0xc3, 0x6c, 0x9a, 0xb3, 0x24,
	0x93, 0x05, 0x53, 0x74, 0x06, 0xff, 0x5b, 0xb2, 0x2d, 0x61, 0x5a, 0x5b, 0x76, 0xa7, 0xd0, 0x50,
	0x3e, 0x54, 0x9a, 0xc7, 0xd5, 0x88, 0x9a, 0x34, 0x2b, 0x85, 0xaa, 0xf2, 0x75, 0xc5, 0x11, 0x6b,
	0xb4, 0x10, 0xd4, 0xc2, 0x98, 0x8d, 0x37, 0xd3, 0x74, 0x83, 0x07, 0xcc, 0xa1, 0xfb, 0xb1, 0x6a,
	0x82, 0x09, 0xa9, 0x16, 0x77, 0xcc, 0x27, 0x26, 0x88, 0x3a, 0x2a, 0xcd, 0x50, 0x48, 0xe3, 0x5c,
	0x1d, 0xc3, 0x97, 0xe0, 0x50, 0x76, 0xa9, 0xd6, 0x41, 0xd3, 0x91, 0x30, 0x03, 0x73, 0x6d, 0x1d,
	0x0a, 0x24, 0xfc, 0xd5, 0x02, 0xff, 0x24, 0x8a, 0x8b, 0x39, 0xa3, 0xf8, 0xf3, 0x1c, 0x85, 0xac,
	0x09, 0xc5, 0x5a, 0x24, 0x14, 0x43, 0x19, 0x76, 0x4d, 0x19, 0x2f, 0xf4, 0xce, 0xe7, 0x8a, 0x5d,
	0x6f, 0x1d, 0xaa, 0x12, 0x25, 0x2f, 0xc0, 0x63, 0x39, 0xf2, 0x48, 0x2a, 0xea, 0x6e, 0x2c, 0x73,
	0x58, 0x8d, 0x85, 0x08, 0x8f, 0x17, 0xb2, 0xb9, 0xf3, 0x63, 0xf0, 0x54, 0xd1, 0x02, 0x9b, 0xa0,
	0x10, 0x38, 0xd5, 0x49, 0xb5, 0x69, 0xad, 0xb8, 0x9b, 0xfd, 0xc2, 0xb7, 0xd0, 0x32, 0xb4, 0xb4,
	0xa2, 0x56, 0x02, 0x0d, 0xc5, 0xf1, 0xa6, 0x58, 0x7d, 0xbe, 0xdf, 0x02, 0xd5, 0x4b, 0xda, 0xb8,
	0x63, 0x49, 0xc3, 0x5d, 0xd8, 0xa4, 0x18, 0x27, 0x42, 0x22, 0x2f, 0xf9, 0xd1, 0xf4, 0x7e, 0x81,
	0x47, 0xad, 0xbb, 0x79, 0xf4, 0x6b, 0xd8, 0x18, 0x62, 0x8a, 0x12, 0x97, 0x3c, 0xdc, 0xbb, 0xa2,
	0xf0, 0x2b, 0x78, 0x72, 0x98, 0x08, 0x69, 0xee, 0x8b, 0xff, 0xee, 0x60, 0x0c, 0x8f, 0xaa, 0xe0,
	0x77, 0x3e, 0xd6, 0x16, 0xb4, 0x4d, 0xda, 0xc2, 0xec, 0xeb, 0x72, 0x59, 0x15, 0xbe, 0xf5, 0x39,
	0xd8, 0x47, 0x39, 0x69, 0x81, 0xb3, 0x33, 0x1c, 0xfa, 0x0f, 0xd4, 0x61, 0x38, 0x3a, 0xf4, 0x2d,
	0xe2, 0x41, 0xf3, 0xd5, 0xe1, 0xe9, 0x78, 0xdf, 0xb7, 0xc9, 0x06, 0xf8, 0x74, 0xb4, 0x77, 0x30,
	0x3e, 0x19, 0xd1, 0x1f, 0x4e, 0xe8, 0xc1, 0xde, 0xde, 0x88, 0xfa, 0xce, 0xd6, 0x07, 0x00, 0x35,
	0xf7, 0x10, 0x17, 0xec, 0x1d, 0xe9, 0x3f, 0x20, 0x00, 0xee, 0x2e, 0x9e, 0x33, 0x8e, 0x85, 0x8b,
	0x9d, 0x73, 0x89, 0xdc, 0xb7, 0xb7, 0xbe, 0xa8, 0xd6, 0x4f, 0x59, 0x8c, 0x93, 0x2c, 0x4e, 0xd1,
	0x7f, 0x40, 0x3a, 0xd0, 0xfa, 0x1e, 0x39, 0x3b, 0xca, 0x94, 0xf9, 0x1a, 0xb4, 0x95, 0x70, 0x9c,
	0xce, 0x85, 0x6f, 0x2b, 0xe8, 0x28, 0x43, 0x2d, 0x38, 0x83, 0x3f, 0x1d, 0x68, 0xee, 0xb3, 0xe9,
	0x70, 0x97, 0x7c, 0x04, 0x6e, 0xf1, 0x3d, 0x21, 0x25, 0xbb, 0x2c, 0x7c, 0x5e, 0xba, 0x8f, 0xca,
	0xbf, 0x15, 0x65, 0x7f, 0x3e, 0x84, 0xe6, 0x37, 0xfa, 0xcf, 0xc9, 0xbd, 0xac, 0x3f, 0x81, 0xb6,
	0xe1, 0x5c, 0x41, 0x9e, 0x18, 0x70, 0x91, 0x84, 0x6f, 0xde, 0xf8, 0x12, 0xbc, 0x6a, 0x83, 0x48,
	0xc9, 0x61, 0xcb, 0x1b, 0xde, 0x0d, 0x6e, 0x02, 0xe6, 0xfe, 0x3e, 0x3c, 0x5a, 0x9a, 0x4c, 0xf2,
	0x6e, 0x15, 0xe3, 0xb6, 0x89, 0xed, 0x6e, 0x2e, 0xbd, 0x64, 0xe9, 0x69, 0x08, 0x0f, 0xaf, 0xcd,
	0x27, 0x79, 0xc7, 0x18, 0xde, 0x36, 0xb5, 0x2b, 0xbd, 0xec, 0xc2, 0xda, 0xe2, 0x8c, 0x92, 0xae,
	0xb1, 0xbb, 0x65, 0x70, 0x57, 0xf9, 0x38, 0x73, 0xb5, 0xfa, 0xd3, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x27, 0x2e, 0xdb, 0x62, 0x75, 0x0a, 0x00, 0x00,
}
